### ISSUE TITLE
Can't finish download all header

### ISSUE THREAD

**Issue by hkkane** [dn0z/Steam-Headers-Downloader#1]
![gggg](https://cloud.githubusercontent.com/assets/16114400/11525801/f91170c6-9910-11e5-909e-85482bbeec4e.jpg)

**Comment by over-engineer** [comment]
Thanks for reporting this issue. Could you please provide the Steam username you're using, so I can try to replicate that bug?

**Comment by hkkane** [comment]
steam id:hkkane

but I solved the problem,possible the download speed too fast!!,
I hear they have the limit on steam side,cannot get to much request within one minute,so I used the slow speed VPN,successed download all header

the tool need add reconnect/retry feature
