### ISSUE TITLE
Syntax error?

### ISSUE THREAD

**Issue by grenadeh** [dn0z/Steam-Headers-Downloader#2]
I have a different issue. Syntax error no matter what. Am using the right Python version, Python itself is working as far as I can tell but no matter what drive I put the .py script in and try to run it from the command prompt, it throws a syntax error in the only line I typed, which is 100% correct.

for example

python.exe C:\steam_headers_download.py 
or
python.exe E:\steam_headers_download.py

**Comment by over-engineer** [comment]
Sorry for my belated reply. Can you please post the syntax error you're getting?

**Comment by over-engineer** [comment]
This issue is now closed, because there's not enough information to reproduce it.
