### ISSUE TITLE
Script simply closes

### ISSUE THREAD

**Issue by xyz404** [dn0z/Steam-Headers-Downloader#3]
Hello
I have completed all the briefings as described. But if I confirm the input, the script closes. 
I am of opinion still briefly a message and to be able to divine before the window is gone. 
What can I do?

**Comment by over-engineer** [comment]
Could you please clarify the issue?

**Comment by xyz404** [comment]
I found the error, the description says: use [http://steamcommunity.com/id/[username]/games?tab=all&xml=1] it was a bit confusing. It should be described in more detail that only the username is needed.
